services:
  mysql:
    image: mysql:8.0.36
    container_name: digital-bank-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: digital_bank
      MYSQL_USER: digital_bank
      MYSQL_PASSWORD: digital_bank
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - digital-bank-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: digital-bank-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend-api:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: digital-bank-backend-api
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:mysql://mysql:3306/digital_bank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: digital_bank
      DB_PASSWORD: digital_bank
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      JWT_SECRET: change-this-secret-change-this-secret
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  notificationservice:
    build:
      context: ./notificationservice
      dockerfile: Dockerfile
    container_name: digital-bank-notification-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  digital-bank-mysql-data:

